// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9DSACDTwILLqQUbDSl5GUMiWpJeSoTUQ',
    appId: '1:247178148577:web:51f1e6386e0eb8af7b55a0',
    messagingSenderId: '247178148577',
    projectId: 'tasks-1d03b',
    authDomain: 'tasks-1d03b.firebaseapp.com',
    storageBucket: 'tasks-1d03b.firebasestorage.app',
    measurementId: 'G-5QHKFPHS19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1L1L1JenxY7ZT9KoKLZGCXlT9hbwoKDE',
    appId: '1:247178148577:android:4719b568f00f42ed7b55a0',
    messagingSenderId: '247178148577',
    projectId: 'tasks-1d03b',
    storageBucket: 'tasks-1d03b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyvqdPviBdt3ZTmCzVYl54X9WcL2e3ZxE',
    appId: '1:247178148577:ios:54eee1d4c9ca6ab07b55a0',
    messagingSenderId: '247178148577',
    projectId: 'tasks-1d03b',
    storageBucket: 'tasks-1d03b.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyvqdPviBdt3ZTmCzVYl54X9WcL2e3ZxE',
    appId: '1:247178148577:ios:54eee1d4c9ca6ab07b55a0',
    messagingSenderId: '247178148577',
    projectId: 'tasks-1d03b',
    storageBucket: 'tasks-1d03b.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9DSACDTwILLqQUbDSl5GUMiWpJeSoTUQ',
    appId: '1:247178148577:web:f802c04e8ae360f47b55a0',
    messagingSenderId: '247178148577',
    projectId: 'tasks-1d03b',
    authDomain: 'tasks-1d03b.firebaseapp.com',
    storageBucket: 'tasks-1d03b.firebasestorage.app',
    measurementId: 'G-GWZKV30MJK',
  );

}